version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "3030:3030"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: placenet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
  
  placenet-backend:
    build:
      context: ./Placenet-App-Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: placenet-backend
    volumes:
      - ./Placenet-App-Backend:/usr/src/app/placenet-backend
      - /usr/src/app/placenet-backend/node_modules

  placenet-app:
    build:
      context: ./Placenet-App-Frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    container_name: placenet-app
    volumes:
      - ./Placenet-App-Frontend:/usr/src/app/placenet-app
      - /usr/src/app/placenet-app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 

volumes:
  postgres-data: